services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
      environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      command: >
        sh -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000 "
      volumes:
        - ..:/app
      ports:
        - "8000:8000"